app: fullstack-serverless-db

component: postgresql
name: fullstack-db

inputs:
  region: ${env:REGION}
  zone: ${env:ZONE}
  dBInstanceName: ${name}
  vpcConfig:
    vpcId: ${output:${stage}:${app}:fullstack-vpc.vpcId}
    subnetId: ${output:${stage}:${app}:fullstack-vpc.subnetId}
  extranetAccess: false
